--- 
Default Meta Description: manticore description
Email: james@eskimosoup.co.uk
Phone: 01482 611888
Newsletter Subscription Page: /pages/newsletter-subscription
Default Meta Tags: manticore, default, tags
Name: Hull Bid
